name: watch
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh watch.sh
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
